<?php

namespace CoreBundle\Repository;

/**
 * JeuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JeuRepository extends \Doctrine\ORM\EntityRepository
{
	public function findJeux($console)
	{
		$queryBuilder = $this->createQueryBuilder('j')
		->where('j.console = :console')
		->setParameter('console', $console);
		
		return $queryBuilder;
	}
}
